[tools]
# Specify Node.js version 23.x
node = "23.0.0"

# Specify pnpm version 10.9.x
pnpm = "10.9.0"

[env]
# Add any environment variables needed for the project here
NODE_ENV = "development"

[tasks]
# Define common tasks for the project
dev = "pnpm run dev"
build = "pnpm run build"
test = "pnpm run test"
lint = "pnpm run lint"
