[tools]
# Specify Node.js version 24.x
node = "24"

# Specify pnpm version 10.12.x
pnpm = "10.12.4"

[env]
# Add any environment variables needed for the project here
NODE_ENV = "development"

[tasks]
# Define common tasks for the project
dev = "pnpm run dev"
build = "pnpm run build"
test = "pnpm run test"
lint = "pnpm run lint"
