coverage:
  status:
    project:
      default:
        target: 95%
        threshold: 0%
    patch:
      default:
        target: 95%
        threshold: 0%
  ignore:
    - "src/types.ts"
    - "src/**/types.ts"
    - "src/constants.ts"
    - "src/**/constants.ts"
    - "scripts/**"
