ARG NODE_ALPINE_NAME=node
ARG NODE_ALPINE_TAG=26-alpine
ARG NODE_ALPINE_DIGEST=sha256:aadf416b2cdce311a8811ba3f0608a61b77dbf997500e2eafe781b51f6a0b019
ARG NODE_ALPINE_IMAGE=${NODE_ALPINE_NAME}:${NODE_ALPINE_TAG}@${NODE_ALPINE_DIGEST}
FROM ${NODE_ALPINE_IMAGE}

RUN apk add --no-cache bash

WORKDIR /app

ARG CODEPENDENCE_VERSION
RUN npm install -g codependence@${CODEPENDENCE_VERSION}

COPY tests/release/fixtures/smoke-package.json ./package.json
COPY tests/release/fixtures/smoke-codependencerc.json ./.codependencerc

CMD ["/bin/sh"]
