export const COMMON_PACKAGES = [
  "lodash",
  "react",
  "react-dom",
  "express",
  "axios",
  "typescript",
  "eslint",
  "prettier",
  "jest",
  "webpack",
  "vite",
  "next",
  "vue",
  "angular",
  "svelte",
  "tailwindcss",
  "prisma",
  "graphql",
  "apollo",
  "redux",
  "mobx",
  "rxjs",
  "date-fns",
  "moment",
  "dayjs",
  "chalk",
  "commander",
  "inquirer",
  "ora",
  "dotenv",
  "nodemon",
  "ts-node",
  "rimraf",
  "concurrently",
];

export const SYMBOLS = {
  success: "\x1b[32m\u2713\x1b[0m",
  error: "\x1b[31m\u2717\x1b[0m",
  warning: "\x1b[33m\u25b2\x1b[0m",
  info: "\x1b[36m\u25c6\x1b[0m",
  pinned: "\x1b[33m\u25a0\x1b[0m",
  dot: "\x1b[90m\u00b7\x1b[0m",
  severityMajor: "\x1b[31m\u25cf\x1b[0m",
  severityMinor: "\x1b[33m\u25cf\x1b[0m",
  severityPatch: "\x1b[32m\u25cf\x1b[0m",
  arrow: "\x1b[36m>\x1b[0m",
  bullet: "\x1b[90m>\x1b[0m",
} as const;

export const RAW_SYMBOLS = {
  success: "\u2713",
  error: "\u2717",
  warning: "\u25b2",
  info: "\u25c6",
  pinned: "\u25a0",
  dot: "\u00b7",
  severityMajor: "\u25cf",
  severityMinor: "\u25cf",
  severityPatch: "\u25cf",
  arrow: ">",
  bullet: ">",
} as const;
