import type { OptionDefinition } from "./types";
import type { DependencyManager } from "../types";
import type { WorkflowArea } from "./types";
import { LANGUAGES, NODE_PACKAGE_MANAGERS, PYTHON_PACKAGE_MANAGERS } from "../providers/constants";

export const ACTION_REF = "yowainwright/codependence@v1";
export const CHECKOUT_REF = "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0";
export const DEFAULT_ACTION_SCHEDULE = "0 9 * * 1";
export const DEFAULT_TOKEN_SECRET = ["CODEPENDENCE", "TOKEN"].join("_");
export const GENERATED_ACTION_HEADER = "# Generated by `codependence init actions`.";
export const ASSIGNMENT_PATTERN = /^([^=]+)=(.+)$/s;
export const CRON_SCHEDULE_PATTERN = /^[0-9*/,-]+(?:\s+[0-9*/,-]+){4}$/;
export const EXACT_TOOL_VERSION_PATTERN = /^v?\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/;
export const UPPERCASE_IDENTIFIER_PATTERN = /^[A-Z_][A-Z0-9_]*$/;
export const GO_TOOLCHAIN_VERSION_PATTERN = /^toolchain\s+go(\S+)\s*$/m;
export const GO_VERSION_PATTERN = /^go\s+(\S+)\s*$/m;
export const GO_MINOR_VERSION_PATTERN = /^\d+\.\d+$/;
export const RUST_TOOLCHAIN_CHANNEL_PATTERN = /^\s*channel\s*=\s*["']([^"']+)["']\s*(?:#.*)?$/m;
export const RUST_TOOLCHAIN_VERSION_PATTERN = /^\d+\.\d+\.\d+$/;
export const REGEX_SPECIAL_CHARACTERS_PATTERN = /[.*+?^${}()|[\]\\]/g;
export const MANAGER_PLACEHOLDER = "<manager>";
export const MISE_VERSION_PATTERN = `^\\s*${MANAGER_PLACEHOLDER}\\s*=\\s*["']([^"']+)["']\\s*$`;
export const TOOL_VERSIONS_VERSION_PATTERN = `^${MANAGER_PLACEHOLDER}\\s+(\\S+)`;
export const ENVIRONMENT_VERSION_PATTERN = `^${MANAGER_PLACEHOLDER}=(\\S+)\\s*$`;

export const NODE_MANAGERS = new Set<DependencyManager>(Object.values(NODE_PACKAGE_MANAGERS));
export const ACTION_MANAGERS = new Set<DependencyManager>([
  ...NODE_MANAGERS,
  PYTHON_PACKAGE_MANAGERS.UV,
  LANGUAGES.GO,
  LANGUAGES.RUST,
  LANGUAGES.DOCKER,
  LANGUAGES.GITHUB_ACTIONS,
]);
export const VERSIONED_MANAGERS = new Set<DependencyManager>([
  ...NODE_MANAGERS,
  PYTHON_PACKAGE_MANAGERS.UV,
  LANGUAGES.GO,
  LANGUAGES.RUST,
]);

export const WORKFLOW_AREAS: WorkflowArea[] = ["node", "python", "go", "rust", "infrastructure"];

export const WORKFLOW_LABELS: Record<WorkflowArea, string> = {
  node: "Node",
  python: "Python",
  go: "Go",
  rust: "Rust",
  infrastructure: "Docker and GitHub Actions",
};

export const OPTION_DEFINITIONS: OptionDefinition[] = [
  { flags: ["-t", "--isTestingCLI"], hasValue: false },
  { flags: ["--isTesting"], hasValue: false },
  { flags: ["-f", "--files"], hasValue: true, isArray: true },
  { flags: ["--target"], hasValue: true, isArray: true },
  { flags: ["--version"], hasValue: true, isArray: true },
  { flags: ["--post-update-command"], hasValue: true, isArray: true },
  { flags: ["--schedule"], hasValue: true, isArray: true },
  { flags: ["--token-secret"], hasValue: true },
  { flags: ["--force"], hasValue: false },
  { flags: ["--lockfile"], hasValue: true },
  { flags: ["-u", "--update"], hasValue: false },
  { flags: ["-r", "--rootDir"], hasValue: true },
  { flags: ["-i", "--ignore"], hasValue: true, isArray: true },
  { flags: ["--debug"], hasValue: false },
  { flags: ["--silent"], hasValue: false },
  { flags: ["-v", "--verbose"], hasValue: false },
  { flags: ["-q", "--quiet"], hasValue: false },
  {
    flags: ["-cds", "--codependencies", "--cds"],
    hasValue: true,
    isArray: true,
  },
  { flags: ["-c", "--config"], hasValue: true },
  { flags: ["-s", "--searchPath"], hasValue: true },
  { flags: ["-y", "--yarnConfig"], hasValue: false },
  { flags: ["--permissive"], hasValue: false },
  { flags: ["-l", "--language"], hasValue: true },
  { flags: ["-h", "--help"], hasValue: false },
  { flags: ["--dry-run", "--dryRun"], hasValue: false },
  { flags: ["--interactive"], hasValue: false },
  { flags: ["--watch"], hasValue: false },
  { flags: ["--noCache", "--no-cache"], hasValue: false },
  { flags: ["--format"], hasValue: true },
  { flags: ["--outputFile", "--output-file"], hasValue: true },
  { flags: ["--level"], hasValue: true },
  { flags: ["-m", "--mode"], hasValue: true },
];

export const HELP_TEXT = `
Codependence - Enforce dependency version policy across your project

Usage: codependence [command] [options]

Commands:
  init [type] [items...]            Initialize Codependence
                                    Types: rc, package, default, actions

Options:
  -t, --isTestingCLI               Enable CLI only testing
  --isTesting                       Enable running fn tests w/o overwriting
  -f, --files [files...]           File glob pattern
  --target [managers...]           Run only selected manager targets
  --version [manager=version...]   Exact tool versions for init actions
  --post-update-command [name=cmd...] Override generated lockfile commands
  --schedule [area=cron...]        Override generated workflow schedules
  --token-secret <name>            GitHub PAT secret name for generated workflows
  --force                           Replace generated workflow files
  --lockfile [policy]              Require lockfiles, or pass false to allow manifest-only updates
  -u, --update                      Update dependencies based on check
  -r, --rootDir <rootDir>          Root directory to start search
  -i, --ignore [ignore...]         Ignore glob pattern
  --debug                           Enable debugging
  --silent                          Enable mainly silent logging
  -v, --verbose                     Enable verbose logging (shows debug info)
  -q, --quiet                       Suppress all output except errors
  -cds, --codependencies [deps...] Dependencies to check
  -c, --config <config>            Path to a config file
  -s, --searchPath <searchPath>    Path to do a config file search
  -y, --yarnConfig                  Enable yarn config support
  --level <level>                   Update level: patch, minor, or major (default: major)
  -m, --mode <mode>                verbose: only listed packages; precise: all except listed
  -l, --language <lang>            Target language (nodejs, go, python, rust, docker, github-actions)
  -h, --help                        Show this help message
  --dryRun                          Show what would change without modifying files
  --interactive                     Choose which packages to update interactively
  --watch                           Watch for changes and re-check continuously
  --noCache                         Disable version caching for fresh results
  --format <type>                   Output format: json, markdown, or table (default: table)
  --outputFile <path>               Write output to file instead of stdout

Examples:
  # Get started
  codependence init                           Interactive setup wizard
  codependence init rc                        Create .codependencerc with all deps pinned
  codependence init rc react lodash           Create .codependencerc with listed deps pinned
  codependence init actions                   Create split dependency update workflows
  codependence init actions --version uv=0.8.0
                                              Supply a missing exact tool version

  # Check and update
  codependence                                Check for outdated dependencies
  codependence --update                       Update all dependencies to latest
  codependence --update --dryRun              Preview changes without modifying files

  # Check and update only specific packages (0.x compatible behavior)
  codependence --codependencies react lodash --update
                                              Only update react and lodash

  # Pin specific packages, update everything else
  codependence --permissive --codependencies react lodash --update
                                              Pin react & lodash, update everything else

  # Explicit compatibility mode: only check/update listed packages
  codependence --mode verbose --codependencies react lodash --update
                                              Only update react and lodash

  # Update level control
  codependence --level minor --update         Only update within same major version
  codependence --level patch --update         Only update within same minor version

  # Selective updates
  codependence --codependencies react vue --update
                                              Only update react and vue
  codependence --update --interactive         Choose which packages to update

  # Monorepo & multi-language
  codependence --files '**/package.json'      Update all package.json files in monorepo
  codependence --language python              Check Python requirements.txt/pyproject.toml
  codependence --language go                  Check Go go.mod dependencies
  codependence --language rust                Check Cargo.toml dependencies
  codependence --language docker              Check Dockerfile image tags
  codependence --language github-actions      Check workflow action refs

  # Development
  codependence --watch                        Watch mode - check every 30 seconds
  codependence --verbose                      Show performance metrics and cache stats
  codependence --noCache                      Bypass cache for fresh results

  # Output formats (useful for CI/CD)
  codependence --format json                  Output as JSON for programmatic use
  codependence --format markdown              Output as Markdown for PR comments
  codependence --format json --outputFile deps.json
                                              Save JSON output to file
`;

export const ARGS_START_INDEX = 2;
