name: codependence trigger release tests

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  release-tests:
    if: github.repository == 'yowainwright/codependence'
    runs-on: ubuntu-latest

    steps:
      - name: Repository dispatch release tests
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: yowainwright/codependence-test
          event-type: codependence_update
