name: update codependencies

on:
  schedule:
    - cron: '0 5 * * 1'

jobs:
  udpate-deps:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.0.0]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.9.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Enable Corepack
        run: corepack enable
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm build
      - run: pnpm run update
      - run: pnpm install --no-frozen-lockfile
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PR_CREATE_TOKEN }}
          commit-message: Update dependencies
          title: '[Codependence]  update dependencies'
          body: |
            ## Dependency updates

            Auto-generated by [codependence][1] using [create-pull-request][2]

            [1]: https://github.com/yowainwright/codependence-cron
            [2]: https://github.com/peter-evans/create-pull-request
          branch: update-dependencies
          labels: codependencies
